export const router=[

    {
        title:'控制台',
        icon:'home',
        key:'/index',
    },
    {
        title:'日志查询',
        icon:'home',
        key:'/index/esblog/list',
    },
    {
        title:'用户管理',
        icon:'laptop',
        key:'/index/user',
        child:
            [
                {
                    title:'用户列表',
                    icon:'laptop',
                    key:'/index/user/list',
                },
                {
                    title:'添加用户',
                    icon:'laptop',
                    key:'/index/user/add',
                    child:
                        [
                            {
                                title:'用户列表',
                                icon:'laptop',
                                key:'/index/user/lista',
                            },
                            {
                                title:'添加用户',
                                icon:'laptop',
                                key:'/index/user/adda',
                            },
                        ]
                },

            ]
    },
    {
        title:'部门管理',
        icon:'bars',
        key:'/index/department',
        child:[
            {key:'/index/department/list',title:'部门列表',icon:''},
            {key:'/index/department/add',title:'添加部门',icon:''},
        ]
    },
    {
        title:'职位管理',
        icon:'edit',
        key:'/index/entry',
        child:[
            {key:'/index/entry/dropdown',title:'职位列表',icon:''},
            {key:'/index/entry/menu',title:'添加职位',icon:''},
        ]
    },
];

